# Generated by Django 5.1.1 on 2024-09-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_admin', '0003_event_alter_contact_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='is_happend',
            new_name='happenedStatus',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='startDate',
        ),
    ]
